// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_LabelCurrent = NULL;lv_obj_t *ui_LabelVoltage = NULL;lv_obj_t *ui_LabelEnergy = NULL;lv_obj_t *ui_LabelPower = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_LabelOnOff = NULL;lv_obj_t *ui_LabelCVCC = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCurrent = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelCurrent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCurrent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelCurrent, 60 );
lv_obj_set_y( ui_LabelCurrent, -92 );
lv_obj_set_align( ui_LabelCurrent, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCurrent,"00.00");
lv_obj_set_style_text_color(ui_LabelCurrent, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCurrent, &ui_font_DSEG7ClassicBold36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelVoltage = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelVoltage, -92 );
lv_obj_set_y( ui_LabelVoltage, -92 );
lv_obj_set_align( ui_LabelVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelVoltage,"00.00");
lv_obj_set_style_text_color(ui_LabelVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelVoltage, &ui_font_DSEG7ClassicBold36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelEnergy = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelEnergy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelEnergy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelEnergy, 60 );
lv_obj_set_y( ui_LabelEnergy, -36 );
lv_obj_set_align( ui_LabelEnergy, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelEnergy,"00.00");
lv_obj_set_style_text_color(ui_LabelEnergy, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelEnergy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelEnergy, &ui_font_DSEG7ClassicBold36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPower = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelPower, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPower, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPower, -92 );
lv_obj_set_y( ui_LabelPower, -36 );
lv_obj_set_align( ui_LabelPower, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPower,"00.00");
lv_obj_set_style_text_color(ui_LabelPower, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPower, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPower, &ui_font_DSEG7ClassicBold36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 129 );
lv_obj_set_y( ui_Label6, -80 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"A");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFF06), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -24 );
lv_obj_set_y( ui_Label5, -80 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"V");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 136 );
lv_obj_set_y( ui_Label8, -24 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Wh");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -21 );
lv_obj_set_y( ui_Label7, -24 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"W");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelOnOff = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelOnOff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOnOff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelOnOff, 128 );
lv_obj_set_y( ui_LabelOnOff, -110 );
lv_obj_set_align( ui_LabelOnOff, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOnOff,"OFF");
lv_obj_set_style_text_color(ui_LabelOnOff, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOnOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelOnOff, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelOnOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelOnOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelOnOff, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelOnOff, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelOnOff, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelOnOff, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCVCC = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelCVCC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCVCC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelCVCC, 148 );
lv_obj_set_y( ui_LabelCVCC, -110 );
lv_obj_set_align( ui_LabelCVCC, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCVCC,"CV");
lv_obj_set_style_text_color(ui_LabelCVCC, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCVCC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCVCC, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelCVCC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelCVCC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelCVCC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelCVCC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelCVCC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelCVCC, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 129 );
lv_obj_set_y( ui_Label1, -96 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"00.0");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_DSEG7ClassicBold8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_LabelCurrent= NULL;
ui_LabelVoltage= NULL;
ui_LabelEnergy= NULL;
ui_LabelPower= NULL;
ui_Label6= NULL;
ui_Label5= NULL;
ui_Label8= NULL;
ui_Label7= NULL;
ui_LabelOnOff= NULL;
ui_LabelCVCC= NULL;
ui_Label1= NULL;

}
